#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  4 23:30:11 2018

@author: poc
"""


class T:
    
    p = 'x'
    computer = "o"

    def __init__(self):
        self.board = [" "] * 9
    
    def print_board(self):
        def wrap(elelemt):
            return " " + str(elelemt) + " "
        board = (
        "   | 1 | 2 | 3 |\n"
        " 1 |{0}|{1}|{2}|\n"
        " — | — + — + — |\n"
        " 2 |{3}|{4}|{5}|\n"            
        " — | — + — + — |\n"
        " 3 |{6}|{7}|{8}|\n"            
        )
        elements = [wrap(el) for el in self.board] 
        print(board.format(*elements))

    def start(self):
        print("These is a game board:\n")
        self.print_board()
        print("type two number separated by space to make a move")
        print(self._update_player_move())
        
        
    def _read_move(self):
        x, y = map(int, input("your move:\n").split(" "))
        ix = (x - 1) * 3 + (y - 1)
        return ix
    
    def _update_player_move(self):
        x, y = map(int, input("your move:\n").split(" "))
        ix = (x - 1) * 3 + (y - 1)
        self.board[ix] = self.p
        self.print_board()
        
        
if __name__ == "__main__":
    t = T()
    t.start()

